Store Entity 생성
f-lab-edu/reservation-system pull request #12
Opened 2022-04-25 03:06 UTC by reneener

#5

2022-04-25 04:58 UTC, f-lab-fi commented on src/main/java/entity/store/OperationTime.java
> +    private Date breakEndTime;
지금은 Setter를 노출했지만, 나중에는 좀 더 표현력 있는 메서드를 통해 애플리케이션 서비스와 도메인 객체가 상호작용할 수 있도록 만드는게 좋습니다.
브레이크 타임과 관련해서 다음과 같은 메서드를 생각해볼 수 있겠죠.

`registBreakTime(Date breakStartTime, Date breakEndTime)`

처럼 메서드를 선언하고 메서드에서 브레이크 타임을 설정하는겁니다.

2022-04-25 05:00 UTC, f-lab-fi commented on src/main/java/entity/store/OperationTime.java
> +    private Date breakEndTime;
그러고 보니 Date를 사용하셨네요.
날짜 관련해서는 Date 클래스가 가지고 있는 문제들 때문에 사용하지 않는 것을 추천합니다.
Java Date를 키워드로 어떤 문제가 있는 클래스인지 찾아보시고, 어떤 클래스가 적합할지도 찾아서 바꿔보시면 좋을 것 같아요.

2022-04-25 05:03 UTC, f-lab-fi commented on src/main/java/entity/store/OperationTime.java
> +    private Date startDate;
혹시 '요일'이라는 정보는 필요 없을까요?
우리가 가게 영업시간을 보다보면 보통 요일 마다 영업시간이 다른 경우를 많이 볼 수 있습니다.
또한 startDate, endDate, breakStartTime, breakEndTime를 사용하여 영업 시간을 서비스에 어떻게 노출해주려고 하는지 계획된게 있을까요?
Date를 사용하는게 적절하지는 않지만 일단 Date는 날짜와 시간을 모두 나타낼 수 있는데, 지금 위 4가지 필드로 어떤 데이터를 나타내고 싶은지가 머리속에 잘 그려지지 않습니다. :)

2022-04-25 05:20 UTC, leechGamer commented on src/main/java/entity/store/OperationTime.java
> +    private Date startDate;
erd에 dayOfWeek 컬럼 정의해 놓았는데 빠진 것 같아요. 
@reneener

2022-04-25 05:30 UTC, leechGamer commented on src/main/java/entity/store/Store.java
> +@Table(name = "store")
저희 테이블 이름 단수로 하는 걸로 통일할까요?
저는 복수로 작업했는데, 어떤게 맞는지 찾아보니까 의견이 분분하네요. 
제가 고칠게요 ~

https://stackoverflow.com/questions/338156/table-naming-dilemma-singular-vs-plural-names

2022-04-27 14:41 UTC, leechGamer requested changes

2022-04-27 14:41 UTC, leechGamer commented on src/main/java/entity/store/OperationTime.java
> +    private Date startDate;
startTime, endTime 컬럼이 되어야 할 것 같아요. 
`startDate` -> `startTime`
`endDate` -> `endTime`

2022-04-27 14:41 UTC, leechGamer commented on src/main/java/entity/store/Store.java
> +    @JoinColumn(nullable = false, name = "companyId")
snake case로 바꾸는게 좋을 것 같아요.

2022-04-27 14:41 UTC, leechGamer commented on src/main/java/entity/store/OperationTime.java
> +@Table(name = "OperationTime")
snake case로 바꾸는게 좋을 것 같아요

https://dzone.com/articles/a-guide-to-sql-naming-conventions
위에 링크를 들어가보면 멘토님이 #14 리뷰에 남겨주신 것처럼 snake 케이스를 선호하는 경향이 있다고 하네요. 
code style이 큰 의미가 있지는 않다고 하네요.

2022-04-27 14:41 UTC, leechGamer commented on src/main/java/entity/company/Company.java
> +package entity;
package 경로가 안맞는거 아닌가요...?

2022-04-27 14:41 UTC, leechGamer commented on src/main/java/entity/contstants/StoreCategory.java
> +package entity;
여기도 package 경로 안맞는 것 같아요~

2022-04-27 14:41 UTC, leechGamer commented on src/main/java/entity/store/Address.java
> +package entity;
여기도 package 경로 안맞는 것 같아요~

2022-04-27 14:41 UTC, leechGamer commented on src/main/java/entity/store/Location.java
> +package entity;
여기도 package 경로 안맞는 것 같아요~

2022-04-27 14:41 UTC, leechGamer commented on src/main/java/entity/store/OperationTime.java
> +package entity;
여기도 package 경로 안맞는 것 같아요~

2022-04-27 14:41 UTC, leechGamer commented on src/main/java/entity/store/Store.java
> +package entity;
여기도 package 경로 안맞는 것 같아요~

2022-04-28 13:04 UTC, leechGamer commented on src/main/java/entity/store/OperationTime.java
> +import java.util.Date;
사용하지 않는 것 같아요. 

control + option + o 하면 자동으로 정리해줘요

2022-04-28 13:18 UTC, leechGamer commented on src/main/java/entity/store/OperationTime.java
> +@NoArgsConstructor
이거랑 @Builder 랑 같이 쓰면 컴파일 에러 나요 ㅠㅠ 

> @Builder와 @NoArgsConstructor를 함께 사용하려면, @AllArgsConstructor도 함께 사용하거나 모든 필드를 가지는 생성자를 직접 만들어 줘야 한다. @Builder를 사용할 때 @NoArgsConstructor뿐만 아니라 손수 만든 다른 생성자가 있다면, 그 때도 모든 필드를 가지는 생성자가 필요하다.

https://blog.leocat.kr/notes/2018/09/02/lombok-using-builder-and-noargsconstructor-together

2022-04-28 13:23 UTC, leechGamer commented on src/main/java/entity/store/OperationTime.java
> +    @Column(nullable = false, name = "store_id")
store <-> operationTime 관계가 1:1 단방향이어서 
여기에 store_id를 넣는 것보다 
store 엔티티에 OneToOne으로 객체를 매핑하는게 좋을 것 같아요.

2022-04-28 13:32 UTC, leechGamer commented on src/main/java/entity/store/OperationTime.java
> +            LocalDateTime startTime,
dayOfWeek이 빠졌어요 ~

2022-04-28 13:37 UTC, leechGamer commented on src/main/java/entity/store/Location.java
> +@Builder
여기도 Builder와 NoArgsConstructor가 같이 쓰였네요 ㅠ

2022-04-28 15:56 UTC, leechGamer approved these changes
💯

2022-04-29 08:26 UTC, merged